packages:
  - guidedtour-node/guidedtour-node-ui/src/main/node
  - guidedtour-node-base/src/main/node
  - guidedtour-node-base/src/main/node/core/guidedtour/guidedtour-api
  - guidedtour-node-base/src/main/node/core/guidedtour/guidedtour-ui
  - guidedtour-node-base/src/main/node/core/guidedtour/guidedtour-xwiki
  - guidedtour-node-base/src/main/node/dev/config
  - guidedtour-webjar/src/main/node
catalog:
  "@jridgewell/remapping": 2.3.5
  "@microsoft/api-extractor": 7.58.7
  "@types/jquery": 4.0.0
  "@types/node": 24.12.2
  "@types/sinon": 21.0.0
  "@vitejs/plugin-vue": 6.0.4
  "@vue/test-utils": 2.4.11
  "@xwiki/platform-model-api": 18.3.0
  "@xwiki/platform-tool-apiextractorconfig": 18.3.0
  "@xwiki/platform-tool-eslintconfig": 18.3.0
  "@xwiki/platform-tool-tsconfig": 18.3.0
  "@xwiki/platform-tool-tsdocconfig": 18.3.0
  "@xwiki/platform-tool-viteconfig": 18.3.0
  dompurify: 3.4.2
  driver.js: 1.3.0
  eslint: 9.39.4
  eventemitter3: 5.0.4
  flush-promises: 1.0.2
  happy-dom: 17.6.3
  jiti: 2.7.0
  jquery: 4.0.0
  lodash-es: 4.18.1
  lz-string: 1.5.0
  publint: 0.3.21
  sinon: 21.1.2
  tippy.js: 6.3.7
  typescript: 5.9.3
  u-node: 0.0.8
  vite: 7.3.2
  vite-plugin-css-injected-by-js: 4.0.1
  vite-plugin-dts: 4.5.4
  vitest: 4.1.5
  vue: 3.5.34
  vue-i18n: 11.2.8
  vue-tippy: 6.7.1
  vue-tsc: 3.2.7
  vuedraggable: 4.1.0

catalogMode: strict
cleanupUnusedCatalogs: true
ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
onlyBuiltDependencies:
  - nx
patchedDependencies:
  ## Can be removed once moving to a 18.4.0+ xwiki platform version
  '@xwiki/platform-tool-eslintconfig@18.3.0': patches/@xwiki__platform-tool-eslintconfig@18.3.0.patch
